export const CART_SET_ITEMS = "CART_SET_ITEMS";
export const CART_SET_LOADING = "CART_SET_LOADING";
export const CART_SET_ERROR = "CART_SET_ERROR";
export const CART_SET_INITIALIZED = "CART_SET_INITIALIZED";

